packages:
  - src
  - webview-ui
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - better-sqlite3
  - core-js
  - esbuild
  - keytar
  - puppeteer-chromium-resolver
  - sharp
